---
title: "Combining_Datasets"
author: "Jack Sudds"
date: "08/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(tidyverse) #install.packages("tidyverse")
library(readxl) #install.packages("readxl")
library(here) #install.packages("here")
library(janitor) #install.packages("janitor")
library(kableExtra) #install.packages("kableExtra")
library(skimr) #install.packages("skimr")
library(dplyr)
```

```{r document startup}

j_samples <- read_excel(here("data", "Samples_Master.xlsx"), sheet = "Jack_samples", n_max = 109)
m_list_samples <- read_excel(here("data", "Samples_Master.xlsx"), sheet = "Masterlist_samples", n_max = 49)

#cleaning the names
j_samples <- j_samples %>%
  janitor::clean_names()
m_list_samples <- m_list_samples %>%
  janitor::clean_names()

#unifying column names
j_samples <- j_samples %>%
  rename(do1_code=sample_id_d01_number)
 
m_list_samples <- m_list_samples %>%
  rename(sample_no=sample_number)

#joining the two together
tot_samples <- m_list_samples %>%
  full_join(j_samples, by = c("sample_no", "do1_code", "site", "secondary_code", "period", "date", "element", "d13c", "d15n"))

#creating individual groups by period
tot_samples_grouped <- tot_samples %>%
  arrange(period)

cats_Anglo_Sax <- tot_samples %>%
  filter(period == "Anglo-Saxon") #%>% remove_empty(which = c("cols"), quiet = TRUE)

cats_Iron_Age <- tot_samples %>%
  filter(period == "Iron Age") #%>% remove_empty(which = c("cols"), quiet = TRUE)

cats_Medieval <- tot_samples %>%
  filter(period == "Medieval") #%>% remove_empty(which = c("cols"), quiet = TRUE)

cats_Post_Med <- tot_samples %>%
  filter(period == "Post-Medieval")#%>% remove_empty(which = c("cols"), quiet = TRUE)

cats_Roman <- tot_samples %>%
  filter(period == "Roman") #%>% remove_empty(which = c("cols"), quiet = TRUE)

cats_Modern_jsample <- tot_samples %>%
  filter(period == "Modern") #%>% remove_empty(which = c("cols"), quiet = TRUE)

```

```{r simple_graphs}
plot_set <- tot_samples

gg_base <- ggplot2::ggplot(data = plot_set, aes(x = d13c, y = d15n))

##now that is done time to make some graphs
gg_base +
  geom_point() +
  aes() +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')) +
      labs(
        x = "δ13C‰",
        y = "δ15N‰",
        title = "Basic plot of tested samples",
        subtitle = "As of 08/08/2020") +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))
      #ggsave(here("figures", "basic_all_tested.jpg"), dpi = 180, width = 8, height = 7)
    
##that worked like a charm now for more complexity
gg_base +
  geom_point() +
  aes(
    color = period
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')) +
      labs(
        x = "δ13C‰",
        y = "δ15N‰",
        title = "Basic plot of tested samples by period",
        subtitle = "As of 08/08/2020") +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)) +
  scale_color_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))
      #ggsave(here("figures", "basic_all_tested_by_period .jpg"), dpi = 180, width = 8, height = 7)
```

```{r period graphs}
#plotting the results by period
by_period_figure <- ggplot2::ggplot(data = tot_samples, aes(x = d13c, y = d15n, group = period))

#all together
by_period_figure +
  geom_point() +
  aes(
    color = period
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white')
        ) +
      labs(
        x = "δ13C‰",
        y = "δ15N‰",
        title = "Basic plot of tested samples",
        subtitle = "As of 08/08/2020",
        color = "Period") +
        facet_wrap(~ period) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "faceted_by_period .jpg"), dpi = 180, width = 8, height = 7)
```

```{r Anglo-Saxon graph}
#Drop empty and unprocessed samples
cats_Anglo_Sax_d <- drop_na(cats_Anglo_Sax, d13c)

#each period colored by site
cats_Anglo_Sax_G <- ggplot2::ggplot(data = cats_Anglo_Sax_d, aes(x = d13c, y = d15n, group = site))

cats_Anglo_Sax_G +
  geom_point(size = 2) +
  aes(
    color = site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Basic Plot of Anglo-Saxon Samples",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "Anglo-Saxon_by_site .jpg"), dpi = 180, width = 8, height = 7)
```

```{r Iron Age}
#Drop empty and unprocessed samples
cats_Iron_Age_d <- drop_na(cats_Iron_Age, d13c)

#each period colored by site
cats_Iron_Age_G <- ggplot2::ggplot(data = cats_Iron_Age_d, aes(x = d13c, y = d15n, group = site))

cats_Iron_Age_G +
  geom_point(size = 2) +
  aes(
    color = site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Basic Plot of Iron Age Samples",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "Iron_Age_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Roman Graphs}
#Drop empty and unprocessed samples
cats_Roman_d <- drop_na(cats_Roman, d13c)

#each period colored by site
cats_Roman_G <- ggplot2::ggplot(data = cats_Roman_d, aes(x = d13c, y = d15n, group = site))

cats_Roman_G +
  geom_point(size = 2) +
  aes(
    color = site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Basic Plot of Roman Samples",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "Roman_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Medieval gragh}
#Drop empty and unprocessed samples
cats_Medieval_d <- drop_na(cats_Medieval, d13c)

#each period colored by site
cats_Medieval_G <- ggplot2::ggplot(data = cats_Medieval_d, aes(x = d13c, y = d15n, group = site))

cats_Medieval_G +
  geom_point(size = 2) +
  aes(
    color = site,
  )+
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Basic Plot of Medieval Samples",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "Medieval_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Post-Medieval}
#Drop empty and unprocessed samples
cats_Post_Med_d <- drop_na(cats_Post_Med, d13c)

#each period colored by site
cats_Post_Med_G <- ggplot2::ggplot(data = cats_Post_Med_d, aes(x = d13c, y = d15n, group = site))

cats_Post_Med_G +
  geom_point(size = 2) +
  aes(
    color = site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Basic Plot of Post-Medieval Samples",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "Post-Medieval_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Modern}
#Drop empty and unprocessed samples
cats_Modern_jsample_d <- drop_na(cats_Modern_jsample, d13c)

#each period colored by site
cats_Modern_jsample_G <- ggplot2::ggplot(data = cats_Modern_jsample_d, aes(x = d13c, y = d15n, group = site))

cats_Modern_jsample_G +
  geom_point(size = 2) +
  aes(
    color = site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Basic Plot of Modern Samples",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

  #ggsave(here("figures", "Modern_from_set_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r collagen percentage graphing}
#change order of periods to chronological - FAILURE
#x1 <- factor(j_samples, levels = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))   

##ANOTHER FAIL
#j_samples_prep <- j_samples %>%
  #fct_relevel(period, "Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")

##third times the charm - SPOILER IT SORT OF WAS
j_samples <- j_samples%>%
  arrange(match(period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")))
  
#make graph
coll_percent_graphing <- ggplot2::ggplot(data = j_samples, aes(x = period, y = collagen_percent, fill = period))

coll_percent_graphing +
   geom_boxplot() +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   geom_point(stat = 'identity', alpha = 0.5) +
   geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
  labs(
    x = "Periods",
    y = "Collagen Percentage Extracted",
    title = "Plot of Percentage of Viable Collagen Extracted"
  ) +
  #changing legend order
  scale_fill_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))
  
```

```{r Nitrogen by period box plot}

tot_samples <- tot_samples%>%
  arrange(match(period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")))
  
#make graph
n_by_period_graphing <- ggplot2::ggplot(data = tot_samples, aes(x = period, y = d15n, fill = period))

n_by_period_graphing +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity', alpha = 0.5) +
   geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
  labs(
    x = "Periods",
    y = "\u03B415N‰",
    title = "Plot of Nitrogen Values by Period") +
  coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)) +
  #changing legend order
  scale_fill_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

##Nitrogen values just points
n_by_period_graphing_points <- ggplot2::ggplot(data = tot_samples, aes(x = period, y = d15n, color = period))

n_by_period_graphing_points +
   #geom_boxplot() +
   #stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   geom_point(stat = 'identity') +
   #geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
  labs(
    x = "Periods",
    y = "\u03B415N‰",
    title = "Plot of Nitrogen Values by Period") +
  coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)) +
  #changing legend order
  scale_color_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))
```

```{r carbon_by_period}
tot_samples <- tot_samples%>%
  arrange(match(period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")))
  
#make graph
c_by_period_graphing <- ggplot2::ggplot(data = tot_samples, aes(x = period, y = d13c, fill = period))

c_by_period_graphing +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity', alpha = 0.5) +
   geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'), 
      ) +
  labs(
    x = "Periods",
    y = "\u03B413C‰",
    title = "Plot of Carbon Values by Period") +
  #coord_cartesian(ylim = c(5,15)) +
  #scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)) +
  #changing legend order
  scale_fill_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

##Carbon values just points
c_by_period_graphing_points <- ggplot2::ggplot(data = tot_samples, aes(x = period, y = d13c, color = period))

c_by_period_graphing_points +
   #geom_boxplot() +
   #stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   geom_point(stat = 'identity') +
   #geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
  labs(
    x = "Periods",
    y = "\u03B413C‰",
    title = "Plot of Carbon Values by Period") +
  #coord_cartesian(ylim = c(5,15)) +
  #scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)) +
  #changing legend order
  scale_color_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))
```

```{r generic code for plotting 1 variable for sites within a period (using Medieval Nitrogen as start)}
##Switching from box plot to point requires tweaking

#sets period and removes any empty values
d15n_in_med <- ggplot2::ggplot(data = subset(tot_samples, period == "Medieval" & !is.na(d15n)), aes(x = site, y = d15n, fill = site))

d15n_in_med +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   geom_jitter(width = 0.2) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')
      ) +
  labs(
    x = "Site",
    y = "\u03B415N‰",
    title = "Plot of Nitrogen Values by Site for Medieval Samples") +
  coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15))
  #changing legend
  #scale_fill_discrete(name = c("Site"),
                      #breaks = c("Bamburgh Castle", "Fishergate", "Wharram Percy"))
```

```{r check that generic graph maker works}
##Switching from box plot to point requires tweaking

#sets period and removes any empty values
d15n_in_Roman <- ggplot2::ggplot(data = subset(tot_samples, period == "Roman" & !is.na(d15n)), aes(x = site, y = d15n, fill = site))

d15n_in_Roman +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_jitter(width = 0) +
  aes(
    #color = site
  ) +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        axis.text.x = element_text(angle = 45, vjust = 0.5)
      ) +
  labs(
    x = "Site",
    y = "\u03B415N‰",
    title = "Plot of Nitrogen Values by Site for Roman Samples") +
  #coord_cartesian(ylim = c(5,15)) +
  #scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)) +
  #changing legend
  scale_fill_discrete(name = c("Site")) +
  scale_color_discrete(name = c("Site"))

```

