---
title: "Graphs for talk"
author: "Jack Sudds"
date: "14/10/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(tidyverse) #install.packages("tidyverse")
library(readxl) #install.packages("readxl")
library(here) #install.packages("here")
library(janitor) #install.packages("janitor")
library(kableExtra) #install.packages("kableExtra")
library(skimr) #install.packages("skimr")
library(dplyr) #install.packages("dplyr")
library(RColorBrewer) #install.packages("RColorBrewer")
library(formattable) #install.packages("formattable")
```

```{r data import}
O_data <- read_excel(here("data", "Returned_Oct.xlsx"), sheet = "data", n_max = 84)

O_data <- O_data %>%
  arrange(Period)

O_data_S <- O_data [complete.cases(O_data$S),]

F_ref_data <- read_excel(here("data", "Returned_Oct.xlsx"), sheet = "Foreign_examples", n_max = 7)

#period sets

O_data_Anglo_Sax <- O_data %>%
  filter(Period == "Anglo-Saxon") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Iron_Age <- O_data %>%
  filter(Period == "Iron Age") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Medieval <- O_data %>%
  filter(Period == "Medieval") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Post_Med <- O_data %>%
  filter(Period == "Post-Medieval")#%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Roman <- O_data %>%
  filter(Period == "Roman") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Modern <- O_data %>%
  filter(Period == "Modern") #%>% remove_empty(which = c("cols"), quiet = TRUE)

#period sets Sulphur

O_data_Anglo_Sax_S <- O_data_S %>%
  filter(Period == "Anglo-Saxon") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Iron_Age_S <- O_data_S %>%
  filter(Period == "Iron Age") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Medieval_S <- O_data_S %>%
  filter(Period == "Medieval") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Post_Med_S <- O_data_S %>%
  filter(Period == "Post-Medieval")#%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Roman_S <- O_data_S %>%
  filter(Period == "Roman") #%>% remove_empty(which = c("cols"), quiet = TRUE)

O_data_Modern_S <- O_data_S %>%
  filter(Period == "Modern") #%>% remove_empty(which = c("cols"), quiet = TRUE)
```

```{r Base graphs}
O_data_new <- O_data%>%
  arrange(match(Period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")))

O_graphing <- ggplot2::ggplot(data = O_data_new, aes(x = C, y = N, color = Period))

O_graphing +
  geom_point() +
  aes() +
  # scale_color_brewer(type = qual, palette = "Set1")+
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white')) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Isotopic analysis of Cat Bone",
        subtitle = "Data avaliable as of 14/10/20") +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = c(-23, -22, -21, -20, -19, -18, -17, -16)) +
  scale_y_continuous(breaks = c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))

ggsave(here("figures", "CarbonNitrogen.pdf"), dpi = 180, width = 8, height = 7)

```

```{r foreign reference C/N}
#dataprep
F_ref_data_m <- F_ref_data

F_ref_data_m$Label <- paste(F_ref_data$Country, F_ref_data$Date, sep = " - ")
  

#each period colored by site
F_ref_data_G <- ggplot2::ggplot(data = F_ref_data_m, aes(x = Carbon, y = Nitrogen, group = Country))

F_ref_data_G +
  geom_point(size = 2) +
  aes(
    color = Label
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "European Archaeological Reference",
        subtitle = "Carbon / Nitrogen",
        color = "Country"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  ggsave(here("figures", "European Archeological Reference.pdf"), dpi = 180, width = 8, height = 7)


```


```{r Carbon and Nitrogen whole dataset}
O_data_new <- O_data%>%
  arrange(match(Period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")))

#make graph
O_data_N <- ggplot2::ggplot(data = O_data_new, aes(x = Period, y = N, fill = Period))

O_data_N +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity', alpha = 0.5) +
   #geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey')
      ) +
  labs(
    x = "Periods",
    y = "\u03B415N‰",
    title = "Plot of Nitrogen Values by Period") +
  coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1)) +
  #changing legend order
  scale_fill_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

ggsave(here("figures", "Nitrogen_box.pdf"), dpi = 180, width = 8, height = 7)


##Nitrogen values just points
O_data_N <- ggplot2::ggplot(data = O_data_new, aes(x = Period, y = N, color = Period))

O_data_N +
   #geom_boxplot() +
   #stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity') +
   geom_jitter(width = 0.1, height = 0) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey')
      ) +
  labs(
    x = "Periods",
    y = "\u03B415N‰",
    title = "Plot of Nitrogen Values by Period") +
  coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1)) +
  #changing legend order
  scale_color_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

ggsave(here("figures", "Nitrogen_dot.pdf"), dpi = 180, width = 8, height = 7)


  
#make graph
O_data_C <- ggplot2::ggplot(data = O_data_new, aes(x = Period, y = C, fill = Period))

O_data_C +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity', alpha = 0.5) +
   #geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey')
      ) +
  labs(
    x = "Periods",
    y = "\u03B413C‰",
    title = "Plot of Carbon Values by Period") +
  #coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  #changing legend order
  scale_fill_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

ggsave(here("figures", "Carbon_box.pdf"), dpi = 180, width = 8, height = 7)


##Carbon values just points
O_data_C <- ggplot2::ggplot(data = O_data_new, aes(x = Period, y = C, color = Period))

O_data_C +
   #geom_boxplot() +
   #stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity') +
   geom_jitter(width = 0.1, height = 0) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'grey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey')
      ) +
  labs(
    x = "Periods",
    y = "\u03B413C‰",
    title = "Plot of Carbon Values by Period") +
  #coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  #changing legend order
  scale_color_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

ggsave(here("figures", "Carbon_dot.pdf"), dpi = 180, width = 8, height = 7)


#make graph
O_data_SG <- ggplot2::ggplot(data = O_data_S, aes(x = Period, y = S, fill = Period))

O_data_SG +
   geom_boxplot(outlier.alpha = 0) +
   stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity', alpha = 0.5) +
   #geom_jitter(width = 0.35, height = 0.1) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey')
      ) +
  labs(
    x = "Periods",
    y = "\u03B434S‰",
    title = "Plot of Sulphur Values by Period") +
  #coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = seq(-7, 12, by = 1), minor_breaks = NULL) +
  #changing legend order
  scale_fill_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

ggsave(here("figures", "Sulphur_box.pdf"), dpi = 180, width = 8, height = 7)


##Carbon values just points
O_data_SG <- ggplot2::ggplot(data = O_data_S, aes(x = Period, y = S, color = Period))

O_data_SG +
   #geom_boxplot() +
   #stat_boxplot(geom = "errorbar", linetype = 1, width = 0.5) +
   #geom_point(stat = 'identity') +
   geom_jitter(width = 0.1, height = 0) +
  scale_x_discrete(limits = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")) +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'grey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey')
      ) +
  labs(
    x = "Periods",
    y = "\u03B434S‰",
    title = "Plot of Sulphur Values by Period") +
  #coord_cartesian(ylim = c(5,15)) +
  scale_y_continuous(breaks = seq(-7, 12, by = 1), minor_breaks = NULL) +
  #changing legend order
  scale_color_discrete(name = "Period",
                      breaks = c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))

ggsave(here("figures", "Sulphur_dot.pdf"), dpi = 180, width = 8, height = 7)


```

```{r faceted}
O_data_new <- O_data%>%
  arrange(match(Period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))) %>%
  mutate(Period = ordered(Period, levels = unique(Period)))

#plotting the results by period
O_data_Facet <- ggplot2::ggplot(data = O_data_new, aes(x = C, y = N, group = Period))

#all together
O_data_Facet +
  geom_point() +
  aes(
    color = Period
  ) +
  scale_color_brewer(palette = "Dark2") +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
        ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Isotopic analysis of Cat Bone",
        subtitle = "Carbon / Nitrogen",
        color = "Period") +
        facet_wrap(vars(Period), scales = "free") +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(3.9,14.2), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(4, 16, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

ggsave(here("figures", "CN_facet.pdf"), dpi = 180, width = 8, height = 5)


#Now with Sulphur

O_data_new <- O_data_S%>%
  arrange(match(Period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern"))) %>%
  mutate(Period = ordered(Period, levels = unique(Period)))

#plotting the results by period
O_data_Facet <- ggplot2::ggplot(data = O_data_new, aes(x = C, y = S, group = Period))

#all together
O_data_Facet +
  geom_point() +
  aes(
    color = Period
  ) +
  scale_color_brewer(palette = "Dark2") +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
        ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B434S‰",
        title = "Isotopic analysis of Cat Bone",
        subtitle = "Carbon / Sulphur",
        color = "Period") +
        facet_wrap(vars(Period), scales = "free") +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(-7, 12), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(-7, 12, by = 2), minor_breaks = NULL)

ggsave(here("figures", "CS_facet.pdf"), dpi = 180, width = 8, height = 5)

```

```{r Anglo-Saxon graph}

#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Anglo_Sax, aes(x = C, y = N, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Anglo-Saxon",
        subtitle = "Carbon / Nitrogen",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  #ggsave(here("figures", "Anglo-Saxon_by_site .jpg"), dpi = 180, width = 8, height = 7)
```

```{r Iron Age}
#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Iron_Age, aes(x = C, y = N, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Iron Age",
        subtitle = "Carbon / Nitrogen",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  #ggsave(here("figures", "Iron_Age_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Roman Graphs}
#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Roman, aes(x = C, y = N, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site
  ) +
      theme(
       plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Roman",
        subtitle = "Carbon / Nitrogen",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  #ggsave(here("figures", "Roman_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Medieval gragh}
#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Medieval, aes(x = C, y = N, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site,
  )+
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Medieval",
        subtitle = "Carbon / Nitrogen",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  #ggsave(here("figures", "Medieval_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Post-Medieval}
#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Post_Med, aes(x = C, y = N, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Post-Medieval",
        subtitle = "Carbon / Nitrogen",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  #ggsave(here("figures", "Post-Medieval_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r Modern}
#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Modern, aes(x = C, y = N, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B415N‰",
        title = "Modern",
        subtitle = "Carbon / Nitrogen",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(4,14), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(5, 15, by = 1), minor_breaks = seq(5.5, 14.5, by = 1))

  #ggsave(here("figures", "Modern_from_set_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```

```{r test table}
#data prep
O_data_tab <- O_data

O_data_tab$C <- formatC(O_data_tab$C, format = "f", digits = 2)
O_data_tab$N <- formatC(O_data_tab$N, format = "f", digits = 2)
O_data_tab$S <- formatC(O_data_tab$S, format = "f", digits = 2)


colnames(O_data_tab)[4] = "\u03B413C‰"
colnames(O_data_tab)[5] = "\u03B415N‰"
colnames(O_data_tab)[6] = "\u03B434S‰"

O_data_tab <- O_data_tab %>%
  arrange(match(Period, c("Iron Age", "Roman", "Anglo-Saxon", "Medieval", "Post-Medieval", "Modern")))


#table print
formattable(O_data_tab, align = c("l", "c", "c", "r", "r", "r"))
```

```{r Anglo-Sax}
#each period colored by site
O_data_G <- ggplot2::ggplot(data = O_data_Anglo_Sax_S, aes(x = C, y = S, group = Site))

O_data_G +
  geom_point(size = 2) +
  aes(
    color = Site
  ) +
      theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor = element_line(color = 'white'),
        strip.background = element_rect(color = 'white', fill = 'white'),
        panel.spacing.x = unit(2, "lines")
      ) +
      labs(
        x = "\u03B413C‰",
        y = "\u03B434S‰",
        title = "Anglo-Saxon",
        subtitle = "Carbon / Sulphur",
        color = "Site"
        ) +
  #axis limits
  coord_cartesian(xlim = c(-23,-16), ylim = c(-7,12), expand = FALSE) +
  #tick marks
  scale_x_continuous(breaks = seq(-23, -16, by = 1), minor_breaks = seq(-22.5, -17.5, by = 1)) +
  scale_y_continuous(breaks = seq(-7, 12, by = 1), minor_breaks = NULL)

  #ggsave(here("figures", "Iron_Age_by_Site.jpg"), dpi = 180, width = 8, height = 7)
```